-- MySQL Script generated by MySQL Workbench
-- Thu Feb  1 12:10:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ejercicio_empresa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ejercicio_empresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ejercicio_empresa` DEFAULT CHARACTER SET utf8 ;
USE `ejercicio_empresa` ;

-- -----------------------------------------------------
-- Table `ejercicio_empresa`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejercicio_empresa`.`departamento` ;

CREATE TABLE IF NOT EXISTS `ejercicio_empresa`.`departamento` (
  `depto_nro` VARCHAR(45) NOT NULL,
  `nombre_depto` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  PRIMARY KEY (`depto_nro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejercicio_empresa`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejercicio_empresa`.`empleado` ;

CREATE TABLE IF NOT EXISTS `ejercicio_empresa`.`empleado` (
  `cod_emp` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `puesto` VARCHAR(45) NULL,
  `fecha_alta` DATETIME NULL,
  `salario` FLOAT NULL,
  `comision` FLOAT NULL,
  `depto_nro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_emp`, `depto_nro`),
  INDEX `fk_empleado_departamento_idx` (`depto_nro` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_departamento`
    FOREIGN KEY (`depto_nro`)
    REFERENCES `ejercicio_empresa`.`departamento` (`depto_nro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Insertar datos en la tabla DEPARTAMENTO
INSERT INTO departamento (depto_nro, nombre_depto, localidad) VALUES
('D-000-1', 'Software', 'Los Tigres'),
('D-000-2', 'Sistemas', 'Guadalupe'),
('D-000-3', 'Contabilidad', 'La Roca'),
('D-000-4', 'Ventas', 'Plata');

-- Insertar datos en la tabla EMPLEADO
INSERT INTO empleado (cod_emp, nombre, apellido, puesto, fecha_alta, salario, comision, depto_nro) VALUES
('E-0001', 'César', 'Piñero', 'Vendedor', '2018-05-12', 80000.00, 15000.00, 'D-000-4'),
('E-0002', 'Yosep', 'Kowaleski', 'Analista', '2015-07-14', 140000.00, 0.00, 'D-000-2'),
('E-0003', 'Mariela', 'Barrios', 'Director', '2014-06-05', 185000.00, 0.00, 'D-000-3'),
('E-0004', 'Jonathan', 'Aguilera', 'Vendedor', '2015-06-03', 85000.00, 10000.00, 'D-000-4'),
('E-0006', 'Mito', 'Barchuk', 'Presidente', '2014-06-05', 190000.00, 0, 'D-000-3'),
('E-0008', 'Liliana', 'González', 'Analista', '2016-09-20', 120000.00, 5000.00, 'D-000-2'),
('E-0009', 'Roberto', 'Ramírez', 'Vendedor', '2017-11-10', 90000.00, 12000.00, 'D-000-4'),
('E-0010', 'Carla', 'Martínez', 'Contador', '2019-02-15', 160000.00, 0.00, 'D-000-3'),
('E-0011', 'Javier', 'Sánchez', 'Desarrollador', '2016-03-25', 75000.00, 0.00, 'D-000-4'),
('E-0012', 'Javier', 'Ramírez', 'Vendedor', '2017-11-10', 90000.00, 12000.00, 'D-000-4');
