-- MySQL Script generated by MySQL Workbench
-- Wed Jan 31 12:12:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema empresa_internet
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema empresa_internet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa_internet` DEFAULT CHARACTER SET utf8;
USE `empresa_internet`;
-- -----------------------------------------------------
-- Table `empresa_internet`.`planes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_internet`.`planes`;
CREATE TABLE IF NOT EXISTS `empresa_internet`.`planes`
(
    `id_plan`     INT         NOT NULL,
    `megas`       VARCHAR(45) NULL,
    `precio`      DECIMAL(10) NULL,
    `descuento`   DECIMAL(2)  NULL,
    `nombre_plan` VARCHAR(45) NULL,
    PRIMARY KEY (`id_plan`)
)
    ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `empresa_internet`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_internet`.`clientes`;
CREATE TABLE IF NOT EXISTS `empresa_internet`.`clientes`
(
    `id_cliente`       INT         NOT NULL,
    `dni`              VARCHAR(45) NOT NULL,
    `nombre`           VARCHAR(45) NOT NULL,
    `fecha_nacimiento` DATETIME    NOT NULL,
    `provincia`        VARCHAR(45) NOT NULL,
    `ciudad`           VARCHAR(45) NOT NULL,
    `apellido`         VARCHAR(45) NOT NULL,
    `id_plan`          INT         NOT NULL,
    PRIMARY KEY (`id_cliente`),
    INDEX `cliente_id_plan_idx` (`id_plan` ASC) VISIBLE,
    CONSTRAINT `cliente_id_plan`
        FOREIGN KEY (`id_plan`)
            REFERENCES `empresa_internet`.`planes` (`id_plan`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;
SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;


-- Insertar datos en la tabla planes
INSERT INTO `empresa_internet`.`planes` (`id_plan`, `megas`, `precio`, `descuento`, `nombre_plan`)
VALUES (1, '100', 1000, 0, 'Plan 1');
INSERT INTO `empresa_internet`.`planes` (`id_plan`, `megas`, `precio`, `descuento`, `nombre_plan`)
VALUES (2, '200', 2000, 10, 'Plan 2');
INSERT INTO `empresa_internet`.`planes` (`id_plan`, `megas`, `precio`, `descuento`, `nombre_plan`)
VALUES (3, '300', 3000, 20, 'Plan 3');
INSERT INTO `empresa_internet`.`planes` (`id_plan`, `megas`, `precio`, `descuento`, `nombre_plan`)
VALUES (4, '400', 4000, 15, 'Plan 4');
INSERT INTO `empresa_internet`.`planes` (`id_plan`, `megas`, `precio`, `descuento`, `nombre_plan`)
VALUES (5, '500', 5000, 5, 'Plan 5');

-- Insertar datos en la tabla clientes
INSERT INTO `empresa_internet`.`clientes` (`id_cliente`, `dni`, `nombre`, `fecha_nacimiento`, `provincia`, `ciudad`,
                                           `apellido`, `id_plan`)
VALUES (1, '12345678', 'Juan', '1990-01-01 00:00:00', 'Buenos Aires', 'La Plata', 'Perez', 1);
INSERT INTO `empresa_internet`.`clientes` (`id_cliente`, `dni`, `nombre`, `fecha_nacimiento`, `provincia`, `ciudad`,
                                           `apellido`, `id_plan`)
VALUES (2, '12345679', 'Pedro', '1990-01-01 00:00:00', 'Córdoba', 'La Plata', 'Perez', 2);
INSERT INTO `empresa_internet`.`clientes` (`id_cliente`, `dni`, `nombre`, `fecha_nacimiento`, `provincia`, `ciudad`,
                                           `apellido`, `id_plan`)
VALUES (3, '12345670', 'Maria', '1990-01-01 00:00:00', 'Buenos Aires', 'La Plata', 'Perez', 3);
INSERT INTO `empresa_internet`.`clientes` (`id_cliente`, `dni`, `nombre`, `fecha_nacimiento`, `provincia`, `ciudad`,
                                           `apellido`, `id_plan`)
VALUES (4, '12345671', 'Jose', '1965-08-01 00:00:00', 'Buenos Aires', 'La Plata', 'Perez', 4);
INSERT INTO `empresa_internet`.`clientes` (`id_cliente`, `dni`, `nombre`, `fecha_nacimiento`, `provincia`, `ciudad`,
                                           `apellido`, `id_plan`)
VALUES (5, '12345672', 'Lucia', '1990-01-01 00:00:00', 'Buenos Aires', 'La Plata', 'Perez', 5);
INSERT INTO `empresa_internet`.`clientes` (`id_cliente`, `dni`, `nombre`, `fecha_nacimiento`, `provincia`, `ciudad`,
                                           `apellido`, `id_plan`)
VALUES (6, '12345673', 'Ana', '2000-01-01 00:00:00', 'Santa Fe', 'La Plata', 'Perez', 1);
INSERT INTO `empresa_internet`.`clientes` (`id_cliente`, `dni`, `nombre`, `fecha_nacimiento`, `provincia`, `ciudad`,
                                           `apellido`, `id_plan`)
VALUES (7, '12345674', 'Carlos', '1990-01-01 00:00:00', 'Buenos Aires', 'La Plata', 'Perez', 2);
INSERT INTO `empresa_internet`.`clientes` (`id_cliente`, `dni`, `nombre`, `fecha_nacimiento`, `provincia`, `ciudad`,
                                           `apellido`, `id_plan`)
VALUES (8, '12345675', 'Fernando', '1995-10-01 00:00:00', 'Buenos Aires', 'La Plata', 'Perez', 3);
INSERT INTO `empresa_internet`.`clientes` (`id_cliente`, `dni`, `nombre`, `fecha_nacimiento`, `provincia`, `ciudad`,
                                           `apellido`, `id_plan`)
VALUES (9, '12345676', 'Mariana', '2001-01-01 00:00:00', 'Buenos Aires', 'La Plata', 'Perez', 4);
INSERT INTO `empresa_internet`.`clientes` (`id_cliente`, `dni`, `nombre`, `fecha_nacimiento`, `provincia`, `ciudad`,
                                           `apellido`, `id_plan`)
VALUES (10, '12345677', 'Julieta', '1990-01-01 00:00:00', 'Buenos Aires', 'La Plata', 'Perez', 5);


-- CONSULTAS

-- 1. Obtener el nombre y apellido de los clientes que tengan el plan 1
SELECT nombre, apellido
FROM clientes
WHERE id_plan = 1;

-- 2. Obtener los planes cuyo precio sea mayor a 1000
SELECT *
FROM planes
WHERE precio > 1000;

-- 3. Obtener los planes cuyas megas sean mayores o iguales a 400
SELECT *
FROM planes
WHERE megas >= 400;

-- 4. Obtener clientes ordenados por nombre
SELECT *
FROM clientes
ORDER BY nombre;

-- 5. Obtener clientes con nombre y apellido en una misma columna
SELECT CONCAT(nombre, ' ', apellido) AS nombre_completo
FROM clientes;

-- 6. Obtener los planes cuyo descuento sea mayor a 10
SELECT *
FROM planes
WHERE descuento > 10;

-- 7. Obtener el nombre, precio total y precio con descuento de los planes
SELECT nombre_plan, precio, ROUND(precio - (precio * descuento / 100), 2) AS precio_con_descuento
FROM planes;

-- 8. Obtener el nombre y precio del plan maás económico
SELECT nombre_plan, precio
FROM planes
ORDER BY precio
LIMIT 1;

-- 9. Obtener el nombre y precio del plan más caro
SELECT nombre_plan, precio
FROM planes
ORDER BY precio DESC
LIMIT 1;

-- 10. Obtener las distintas provincias de los clientes
SELECT DISTINCT provincia
FROM clientes;

-- 11. Obtener los clientes que hayan nacido después del 01/01/1990
SELECT *
FROM clientes
WHERE YEAR(fecha_nacimiento) > 1990;
