-- MySQL Script generated by MySQL Workbench
-- Wed Jan 31 12:28:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresa_internet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa_internet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa_internet` DEFAULT CHARACTER SET utf8 ;
USE `empresa_internet` ;

-- -----------------------------------------------------
-- Table `empresa_internet`.`plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_internet`.`plan` ;

CREATE TABLE IF NOT EXISTS `empresa_internet`.`plan` (
  `idplan` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `velocidad` INT NULL,
  `precio` FLOAT NULL,
  `descuento` FLOAT NULL,
  PRIMARY KEY (`idplan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_internet`.`provincia` ;

CREATE TABLE IF NOT EXISTS `empresa_internet`.`provincia` (
  `idprovincia` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idprovincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_internet`.`ciudad` ;

CREATE TABLE IF NOT EXISTS `empresa_internet`.`ciudad` (
  `idciudad` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `provincia_idprovincia` INT NOT NULL,
  PRIMARY KEY (`idciudad`, `provincia_idprovincia`),
  INDEX `fk_ciudad_provincia1_idx` (`provincia_idprovincia` ASC) VISIBLE,
  CONSTRAINT `fk_ciudad_provincia1`
    FOREIGN KEY (`provincia_idprovincia`)
    REFERENCES `empresa_internet`.`provincia` (`idprovincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_internet`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa_internet`.`cliente` ;

CREATE TABLE IF NOT EXISTS `empresa_internet`.`cliente` (
  `idCliente` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `fechaNacimiento` DATETIME NULL,
  `dni` VARCHAR(45) NULL,
  `plan_idplan` INT NOT NULL,
  `ciudad_idciudad` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `plan_idplan`, `ciudad_idciudad`),
  INDEX `fk_cliente_plan_idx` (`plan_idplan` ASC) VISIBLE,
  INDEX `fk_cliente_ciudad1_idx` (`ciudad_idciudad` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_plan`
    FOREIGN KEY (`plan_idplan`)
    REFERENCES `empresa_internet`.`plan` (`idplan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_ciudad1`
    FOREIGN KEY (`ciudad_idciudad`)
    REFERENCES `empresa_internet`.`ciudad` (`idciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `empresa_internet`.`provincia`
(`idprovincia`,
`nombre`)
VALUES
(1,
"Cordoba");

INSERT INTO `empresa_internet`.`ciudad`
(`idciudad`,
`nombre`,
`provincia_idprovincia`)
VALUES
(1,
"Cordoba",
1);

INSERT INTO `empresa_internet`.`plan`
(`idplan`,
`nombre`,
`velocidad`,
`precio`,
`descuento`)
VALUES
(1,
"Basico",
50,
2000,
20),
(2,
"Semi-avanzado",
100,
3000,
30),
(3,
"Avanzado",
150,
3500,
35),
(4,
"Semi-Profesional",
200,
4000,
40),
(5,
"Profesional",
300,
5000,
50);


INSERT INTO `empresa_internet`.`cliente`
(`idCliente`,
`nombre`,
`apellido`,
`fechaNacimiento`,
`dni`,
`plan_idplan`,
`ciudad_idciudad`)
VALUES
(1,"Juan","Perez","1994-06-12",30000000,1,1),
(2,"Jose","Juarez","1995-06-12",40000000,2,1),
(3,"Pedro","Marquez","1990-07-15",35000000,2,1),
(4,"Maria","Perez","1996-06-29",45000000,3,1),
(5,"Juana","Marquez","2000-06-12",39000000,5,1),
(6,"Rosa","Juarez","2001-06-12",60000000,4,1),
(7,"Guillermo","Tagliaferri","1994-06-12",38000000,3,1),
(8,"Jesus","Perez","1999-06-12",45000000,1,1),
(9,"Camila","Perez","1994-06-12",30000000,5,1),
(10,"Marcos","Perez","1994-06-12",90000000,2,1);


